name: shareholder_benefits_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.4
  auto_animated: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
   android: true
   ios: true
   image_path: 'assets/icon/icon.png'
   adaptive_icon_background: '#ffffff'
   adaptive_icon_foreground:  'assets/icon/icon.png'

flutter:
  uses-material-design: true


